Map<String, String> svgLinksMap = {
  "dart": "Photos/Dart-Dark.svg",
  "flutter": "Photos/Flutter-Dark.svg",
  "git": "Photos/Git.svg",
  "github": "Photos/Github-Dark.svg",
  "golang": "Photos/GoLang.svg",
  "mysql": "Photos/MySQL-Dark.svg",
  "postman": "Photos/Postman.svg",
  "c": "Photos/C.svg",
  "cpp": "Photos/CPP.svg",
  "vscode": "Photos/VSCode-Dark.svg",
  "androidstudio": "Photos/AndroidStudio-Dark.svg",
  "html": "Photos/HTML.svg",
  "css": "Photos/css.svg",
  "javascript": "Photos/JavaScript.svg",
  "php": "Photos/PHP-Dark.svg",
  "photoshop": "Photos/Photoshop.svg",
  "adobexd": "Photos/XD.svg",
  "adobeillustrator": "Photos/Illustrator.svg",
};
